name: Build and deploy project docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.eraser/**'
      - 'mkdocs.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Prepare docs files
        run: | 
          python ./docs/prepare_docs.py
          mv $PWD/.eraser/* $PWD/docs/img

      - name: Install mkdocs
        run: pip install mkdocs

      - name: Build docs site
        run: mkdocs build

      - name: Deploy docs to GH pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site